### ISSUE TITLE
No way to get the RowCount

### ISSUE THREAD

**Issue by Himanshuarora97** [marlimox/AloeStackView#75]
Currently, there is no functionality in **AloeStackView** which will give us number of rows present in AloeStackView.
As of now to get the total number of rows I used `aloeStackView.getAllRows().count` which is not an efficient solution as it always creates a new list of UIView

**Comment by thecoolwinter** [comment]
It looks like it's actually fairly efficient. The view doesn't hold a strong reference to each cell, so it loops through each view in the stackView. 

It's just looping through the views it has already layed out. So, it shouldn't be making a large impact on performance.
